---
- name: Disable ipv6 for all
  sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: '1'
    state: present

- name: Check rp_filter value
  sysctl:
    name: net.ipv4.conf.all.rp_filter
    value: '0'
    state: present

- name: Check ipv4 forward
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
